# Problem 002: Even Fibonacci numbers
#---------------------------------------------------------------------------------------------------
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#---------------------------------------------------------------------------------------------------
# main(<input 1>)
#   <input 1> positive integer
#   outputs the sum of all positive Fibonacci numbers less than or equal to <input>
#     <optional input 2> starting number in series (default = 0)
#     <optional input 3> second number in series (default = 1)
#     <optional input 4> starting total (default = 0)
#

def main(max, a=0, b=1, total = 0)
  total += a if a % 2 ==0
  return total if b > max
  main(max, b, a + b, total)
end

#---------------------------------------------------------------------------------------------------

euler_input = 4_000_000
puts main(euler_input)

